language: node_js
node_js:
  - "5"
  - "4"
  - "0.12"

before_install:
  - npm install jshint -g
  - npm install mocha -g
  - npm install istanbul -g
  - export PORT=3000

script:
  - npm run lint
  - npm run coverage

after_script:
  - npm run coveralls
